import { useCallback, useEffect, useRef, useState } from "react";
import { toDataURL } from "qrcode";
import jsQR from "jsqr";
import { generateSeamToken, seamCommitment, SEAM_TOKEN_BYTES } from "@mohar/crypto-core";
import { api } from "../lib/api";
import { Card } from "./ui";

/**
 * ── The seam seal, on the workflow page ──────────────────────────────────────
 *
 * Fit: the browser generates a 32-byte token, sends the server only
 * sha256(token ‖ packageId), and draws the token as a QR code to be printed and
 * stuck across the package's opening flap. The token is shown once and kept
 * nowhere — close this page and the only copy is the label.
 *
 * Test: the laptop camera reads a flap code and asks the server whether it opens
 * the commitment. That is all it does. It authorises nothing and records
 * nothing; the check that decides anything runs inside the access engine at
 * unlock.
 *
 * In the full design the token is generated by `sealkeys`, not a browser, and
 * the commitment goes onto the chain inside `PACKAGE_SEALED`. Neither is built,
 * so this panel stands in for them and says so.
 *
 * The code is version 2, ECC L, raw 32 bytes — the docs/13 label specification.
 */

const toHex = (bytes: ArrayLike<number>): string =>
  Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");

type TestResult = "match" | "mismatch" | "not_fitted" | "unknown_package";

const RESULT_TEXT: Record<TestResult, { tone: string; text: string }> = {
  match: { tone: "ok", text: "This code opens the commitment fitted to this package." },
  mismatch: {
    tone: "critical",
    text: "This code read cleanly but does not open this package's commitment. It is not the label that was fitted here.",
  },
  not_fitted: { tone: "info", text: "No seam seal is fitted to this package, so there is nothing to test against." },
  unknown_package: { tone: "info", text: "The server does not know this package." },
};

export function SeamSealPanel({
  packageId,
  seamProtected,
}: {
  packageId: string;
  seamProtected: boolean;
}) {
  const [fitted, setFitted] = useState(seamProtected);
  const [qr, setQr] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const [scanning, setScanning] = useState(false);
  const [read, setRead] = useState<string | null>(null);
  const [result, setResult] = useState<TestResult | null>(null);

  const videoRef = useRef<HTMLVideoElement | null>(null);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const frameRef = useRef<number | null>(null);

  useEffect(() => setFitted(seamProtected), [seamProtected]);

  const fit = useCallback(async () => {
    setBusy(true);
    setError(null);
    try {
      const token = generateSeamToken();
      await api.fitSeamSeal(packageId, seamCommitment(token, packageId));
      // Raw bytes in byte mode keeps the symbol at version 2 with zero spare
      // capacity; encoding the hex string instead would double it to version 4.
      const url = await toDataURL([{ data: new Uint8ClampedArray(token), mode: "byte" }], {
        errorCorrectionLevel: "L",
        version: 2,
        margin: 4,
        scale: 10,
      });
      token.fill(0); // the only copy left is the image on screen
      setQr(url);
      setFitted(true);
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(false);
    }
  }, [packageId]);

  const stopScan = useCallback(() => {
    if (frameRef.current !== null) cancelAnimationFrame(frameRef.current);
    frameRef.current = null;
    streamRef.current?.getTracks().forEach((t) => t.stop());
    streamRef.current = null;
    setScanning(false);
  }, []);

  useEffect(() => stopScan, [stopScan]);

  const test = useCallback(
    async (tokenHex: string) => {
      try {
        const r = await api.testSeamToken(packageId, tokenHex);
        setResult(r.result);
      } catch (e) {
        setError((e as Error).message);
      }
    },
    [packageId],
  );

  const startScan = useCallback(async () => {
    setError(null);
    setRead(null);
    setResult(null);
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: { facingMode: "environment", width: { ideal: 1280 } },
      });
      streamRef.current = stream;
      const video = videoRef.current;
      if (!video) return;
      video.srcObject = stream;
      await video.play();
      setScanning(true);

      const tick = () => {
        const v = videoRef.current;
        const c = canvasRef.current;
        if (!v || !c || v.readyState < 2) {
          frameRef.current = requestAnimationFrame(tick);
          return;
        }
        c.width = v.videoWidth;
        c.height = v.videoHeight;
        const ctx = c.getContext("2d", { willReadFrequently: true });
        if (!ctx) return;
        ctx.drawImage(v, 0, 0, c.width, c.height);
        const img = ctx.getImageData(0, 0, c.width, c.height);
        const code = jsQR(img.data, img.width, img.height, { inversionAttempts: "dontInvert" });

        // Only a 32-byte payload is a seam token. Anything else — a transit code,
        // a URL, someone's phone number — is ignored rather than sent anywhere.
        if (code && code.binaryData.length === SEAM_TOKEN_BYTES) {
          const hex = toHex(code.binaryData);
          setRead(hex);
          stopScan();
          void test(hex);
          return;
        }
        frameRef.current = requestAnimationFrame(tick);
      };
      frameRef.current = requestAnimationFrame(tick);
    } catch (e) {
      const err = e as Error;
      setError(
        err.name === "NotAllowedError"
          ? "Camera permission was refused. Browsers only offer it on localhost or over https."
          : err.message,
      );
      stopScan();
    }
  }, [stopScan, test]);

  return (
    <Card title="Seam seal" hint={fitted ? "fitted" : "not fitted"}>
      <div style={{ display: "grid", gap: 10, fontSize: 13 }}>
        {!fitted && (
          <>
            <div>
              A QR code across the opening flap. Opening the flap tears it through its
              corner squares, and a torn code cannot be read at all.
            </div>
            <button className="btn primary" onClick={fit} disabled={busy}>
              {busy ? "Fitting…" : "Fit seam seal"}
            </button>
          </>
        )}

        {qr && (
          <div style={{ display: "grid", gap: 6, justifyItems: "center" }}>
            <img src={qr} alt="Seam seal code to print across the flap" style={{ width: 200 }} />
            <div className="note" style={{ margin: 0 }}>
              Print this now and stick it across the flap. It is shown once — the server
              holds only a hash of it, and leaving this page discards the last copy.
            </div>
          </div>
        )}

        {fitted && (
          <>
            <button className="btn" onClick={scanning ? stopScan : startScan}>
              {scanning ? "Stop camera" : "Test a flap code with the camera"}
            </button>
            <video
              ref={videoRef}
              muted
              playsInline
              style={{ width: "100%", borderRadius: 6, display: scanning ? "block" : "none" }}
            />
            <canvas ref={canvasRef} style={{ display: "none" }} />
            {scanning && <div style={{ color: "var(--text-faint)" }}>Looking for a seam code…</div>}
          </>
        )}

        {read && (
          <div style={{ fontFamily: "var(--mono, monospace)", fontSize: 11, wordBreak: "break-all" }}>
            read {read.slice(0, 16)}…{read.slice(-8)}
          </div>
        )}

        {result && (
          <div className={`badge ${RESULT_TEXT[result].tone}`} style={{ whiteSpace: "normal" }}>
            {RESULT_TEXT[result].text}
          </div>
        )}

        {error && <div style={{ color: "var(--critical, #c33)" }}>{error}</div>}

        <div style={{ color: "var(--text-faint)", fontSize: 11 }}>
          A test authorises nothing. The paper opens only through the ceremony, where the
          access engine runs this check with the other 21. Here the browser stands in for{" "}
          <code>sealkeys</code>, which is not built.
        </div>
      </div>
    </Card>
  );
}
