import {
  combineOpeningKey,
  QUICKNET,
  shareContext,
  unwrapControlPart,
  unwrapShareWithSecret,
  type ControlEnvelope,
  type FieldShare,
} from "@mohar/crypto-core";
import { api, type OfficialResult } from "./api";
import { keyStore, loadIdentity, pairThisBrowser } from "./witness";

/**
 * ── This browser as the opening station ──────────────────────────────────────
 *
 * At an opening, the station is the thing that holds the wrapped shares, takes
 * the published beacon, and assembles the key. The ESP32 station does not do
 * that yet, so a paired browser does: it is an enrolled `centre_pc` device with
 * a second key of its own for unwrapping.
 *
 * That second key is an X25519 key generated by the browser as non-extractable
 * and kept in IndexedDB beside the signing key. The ledger is given its public
 * half and wraps each official's share to it when the roster is locked. From
 * then on the ledger holds ciphertext it cannot read, and this page can ask the
 * browser to do the key agreement but cannot read the private key out.
 *
 * The shares and the assembled key exist only in the memory of the page that
 * runs the ceremony. Nothing here writes them to storage, and a reload in the
 * middle of a ceremony loses them: the ceremony is started again, and the
 * abandoned one stays on record.
 */

const X25519 = { name: "X25519" } as const;
const unwrapKeyId = (deviceId: string) => `${deviceId}:unwrap`;

export interface Station {
  deviceId: string;
  wrapPublicHex: string;
}

const toHex = (b: Uint8Array) => [...b].map((x) => x.toString(16).padStart(2, "0")).join("");
const fromHex = (h: string) =>
  Uint8Array.from(h.match(/../g) ?? [], (x) => Number.parseInt(x, 16));

async function unwrapKeyPair(deviceId: string): Promise<CryptoKeyPair | undefined> {
  return keyStore<CryptoKeyPair | undefined>("readonly", (s) => s.get(unwrapKeyId(deviceId)));
}

/** The station this browser already is, if it is one. Reads only. */
export async function currentStation(): Promise<Station | null> {
  const identity = loadIdentity();
  if (!identity) return null;
  const pair = await unwrapKeyPair(identity.deviceId).catch(() => undefined);
  if (!pair) return null;
  const pub = new Uint8Array(await crypto.subtle.exportKey("raw", pair.publicKey));
  return { deviceId: identity.deviceId, wrapPublicHex: toHex(pub) };
}

/**
 * Make this browser a station: pair it as a device if it is not one, give it an
 * unwrap key if it has none, and register the public half with the ledger.
 */
export async function becomeStation(): Promise<Station> {
  const identity = loadIdentity() ?? (await pairThisBrowser());
  let pair = await unwrapKeyPair(identity.deviceId);
  if (!pair) {
    try {
      pair = (await crypto.subtle.generateKey(X25519, false, ["deriveBits"])) as CryptoKeyPair;
    } catch {
      throw new Error(
        "This browser cannot create a non-extractable X25519 key. Use a current Chrome, Edge, " +
          "Firefox or Safari as the station.",
      );
    }
    await keyStore("readwrite", (s) => s.put(pair, unwrapKeyId(identity.deviceId)));
  }
  const wrapPublicHex = toHex(new Uint8Array(await crypto.subtle.exportKey("raw", pair.publicKey)));
  // The ledger accepts the same key again and refuses a different one, so this
  // is safe to repeat and loud if this browser's key was lost and remade.
  await api.registerWrapKey(identity.deviceId, wrapPublicHex);
  return { deviceId: identity.deviceId, wrapPublicHex };
}

/** One official's share, unwrapped, as `combineOpeningKey` takes it. */
export async function unwrapOfficialShare(
  station: Station,
  packageId: string,
  result: OfficialResult,
): Promise<FieldShare> {
  if (!result.share || !result.official) throw new Error("no share was released for this official");
  const pair = await unwrapKeyPair(station.deviceId);
  if (!pair) throw new Error("this browser's unwrap key is gone; it can no longer act as this station");

  const ephemeral = await crypto.subtle.importKey(
    "raw",
    fromHex(result.share.wrapped.ephemeralPublicHex) as BufferSource,
    X25519,
    false,
    [],
  );
  const shared = new Uint8Array(
    await crypto.subtle.deriveBits({ name: "X25519", public: ephemeral }, pair.privateKey, 256),
  );
  const share = unwrapShareWithSecret(
    result.share.wrapped,
    shared,
    station.wrapPublicHex,
    shareContext(packageId, result.share.holder, result.official.personId),
  );
  return {
    index: result.share.index,
    holder: result.share.holder,
    institution: result.share.institution,
    commitment: result.share.commitment,
    share,
  };
}

export class RoundNotPublished extends Error {
  override readonly name = "RoundNotPublished";
}

/** Public relays for the quicknet chain. Any one of them will do. */
const RELAYS = ["https://api.drand.sh", "https://drand.cloudflare.com"];

/**
 * Ask the public beacon for one round.
 *
 * Before the round's time there is nothing to fetch, and that is the answer:
 * the control room's part cannot be opened because the value that opens it does
 * not exist yet, anywhere.
 */
export async function fetchBeacon(round: number): Promise<{ round: number; signature: string }> {
  let last = "";
  for (const relay of RELAYS) {
    try {
      const res = await fetch(`${relay}/${QUICKNET.chainHash}/public/${round}`, {
        signal: AbortSignal.timeout(8000),
      });
      if (res.ok) {
        const b = (await res.json()) as { round: number; signature: string };
        return { round: b.round, signature: b.signature };
      }
      last = `${relay} answered ${res.status}`;
      if (res.status === 404 || res.status === 425) {
        throw new RoundNotPublished(`drand has not published round ${round} yet`);
      }
    } catch (err) {
      if (err instanceof RoundNotPublished) throw err;
      last = `${relay}: ${(err as Error).message}`;
    }
  }
  throw new Error(`Could not reach a drand relay for round ${round} (${last}).`);
}

/**
 * Open the control room's part with the published round, combine it with the
 * two officials' shares, and return the opening key as hex.
 */
export async function assembleOpeningKey(
  envelope: unknown,
  shares: readonly FieldShare[],
  commitments: { controlCommitment: string; keyCommitment: string },
): Promise<string> {
  const env = envelope as ControlEnvelope;
  const beacon = await fetchBeacon(env.round);
  const controlPart = await unwrapControlPart(env, beacon);
  const key = await combineOpeningKey(controlPart, shares, commitments);
  return toHex(key);
}
